# Generated by Django 5.1.6 on 2025-03-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forecast_date', models.DateTimeField()),
            ],
        ),
    ]
