# Generated by Django 5.1.6 on 2025-03-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=111)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=33)),
                ('due_date', models.DateTimeField(verbose_name='Deadline')),
            ],
        ),
    ]
